baseurl = "https://gsomix.github.io/blog/"
languageCode = "en-us"
title = "gsomix.github.io"
theme = "hugo-xmin"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "â†©"

[permalinks]
    posts = "/:filename/"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 3
[[menu.main]]
    name = "RSS"
    url = "rss.xml"

[params]
    description = "A website built through Hugo and Hugo XMin theme."
    footer = "&copy; gsomix 2017 -- 2020 | [Github](https://github.com/gsomix)"

[outputs]
    home = [ "RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "vs"
    tabWidth = 4